# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adf_tests_panel_cpp <- function(y, pmin, pmax, ic, dc, detr, ic_scale, h_rs, range) {
    .Call(`_bootUR_adf_tests_panel_cpp`, y, pmin, pmax, ic, dc, detr, ic_scale, h_rs, range)
}

adf_panel_bootstrap_dgp_cpp <- function(y, pmin, pmax, ic, dc, QD, trim, ic_scale, h_rs, range) {
    .Call(`_bootUR_adf_panel_bootstrap_dgp_cpp`, y, pmin, pmax, ic, dc, QD, trim, ic_scale, h_rs, range)
}

bootstrap_cpp <- function(B, u, e, boot, l, s, ar, ar_est, y0, pmin, pmax, ic, dc, detr, ic_scale, h_rs, range, joint = TRUE, do_parallel = FALSE, nc = 1L, show_progress = FALSE) {
    .Call(`_bootUR_bootstrap_cpp`, B, u, e, boot, l, s, ar, ar_est, y0, pmin, pmax, ic, dc, detr, ic_scale, h_rs, range, joint, do_parallel, nc, show_progress)
}

scaling_factors_cpp <- function(u, prob) {
    .Call(`_bootUR_scaling_factors_cpp`, u, prob)
}

union_tests_cpp <- function(t, s) {
    .Call(`_bootUR_union_tests_cpp`, t, s)
}

union_test_cpp <- function(t, s) {
    .Call(`_bootUR_union_test_cpp`, t, s)
}

BSQT_cpp <- function(pvec, test_i, t_star, level) {
    .Call(`_bootUR_BSQT_cpp`, pvec, test_i, t_star, level)
}

iADF_cpp <- function(test_i, t_star, level) {
    .Call(`_bootUR_iADF_cpp`, test_i, t_star, level)
}

FDR_cpp <- function(test_i, t_star, level) {
    .Call(`_bootUR_FDR_cpp`, test_i, t_star, level)
}

